from .BaseWidget import BaseWidget
from .FooterWidget import FooterWidget
from .HeaderWidget import HeaderWidget
from .LooperWidget import LooperWidget
from .ParamWidget import ParamWidget
from .PlotterWidget import PlotterWidget
from .SidebarWidget import SidebarWidget
from .SolverWidget import SolverWidget
from .SystemWidget import SystemWidget